### ISSUE TITLE
你他妈谁啊？我都没有关注你，你为什么盗我号给你自己点Star？

### ISSUE THREAD

**Issue by 0x8235** [WuDuShanCheng/front-show#1]

**Comment by WuDuShanCheng** [comment]
我不知道 我只是在闲鱼上看见有人说可以给点star而已


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WuDuShanCheng/front-show"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月17日(星期天) 中午12:28
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[WuDuShanCheng/front-show] 你他妈谁啊？我都没有关注你，你为什么盗我号给你自己点Star？ (Issue #1)

**Comment by 0x8235** [comment]
闲鱼上谁啊？盗我号！

**Comment by WuDuShanCheng** [comment]
这个我就不知道了 就是那种帮点star的 我之前还以为他们是有帮点群什么的 也没想到他们是盗号来点的&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WuDuShanCheng/front-show"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月17日(星期天) 晚上10:31
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [WuDuShanCheng/front-show] 你他妈谁啊？我都没有关注你，你为什么盗我号给你自己点Star？ (Issue #1)





 
闲鱼上谁啊？盗我号！

**Comment by 0x8235** [comment]
好的，我大概弄清楚了！GitStar这个，我去他们平台注册过，号称免费的，然后他们就盗了我的号。

**Comment by WuDuShanCheng** [comment]
应该是的 留了尾巴啥的




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WuDuShanCheng/front-show"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年7月17日(星期天) 晚上10:45
***@***.***&gt;;
***@***.***&gt;;"State ***@***.***&gt;;
主题:&nbsp;Re: [WuDuShanCheng/front-show] 你他妈谁啊？我都没有关注你，你为什么盗我号给你自己点Star？ (Issue #1)





 
好的，我大概弄清楚了！GitStar这个，我去他们平台注册过，号称免费的，然后他们就盗了我的号。

**Comment by 0x8235** [comment]
我问了其他同样问题的网友，这个叫王世举的太坏了！做个网站骗大家 Token，然后拿去卖！
谢谢！多有打扰！
