### ISSUE TITLE
作者是个傻逼！专门盗我号给他自己刷星星！干！

### ISSUE THREAD

**Issue by luluchou** [WuDuShanCheng/front-show#2]
我都没看过这个领域，怎么就莫名其妙的点了星星？

**Comment by WuDuShanCheng** [comment]
唉 这个之前有个人也是这样问的 我是找别人帮忙点的星星 估计是你用别人的插件被记录了token... 我啥读不知道 还被骂...
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "WuDuShanCheng/front-show"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年9月16日(星期五) 中午12:53
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[WuDuShanCheng/front-show] 作者是个傻逼！专门盗我号给他自己刷星星！干！ (Issue #2)





 
我都没看过这个领域，怎么就莫名其妙的点了星星？

**Comment by WuDuShanCheng** [comment]
我是真的服了... 我盗你号有病吗 我叫别人帮忙点的

**Comment by WuDuShanCheng** [comment]
估计你用别人的插件被记录token了 不要一上来就骂人好不好

**Comment by WuDuShanCheng** [comment]
你看之前有个人的提问好不好...
